Feature/ci2 cris 5/institution
ci2-ipt/Ci2-CRIS pull request #50
Opened 2023-01-25 00:56 UTC by LammLamm12

Model done and ready to send to main.
Still no images in active record.

2023-01-25 03:27 UTC, curiousyigit requested changes
Please rename the PR according to our conventions

2023-01-28 20:00 UTC, curiousyigit requested changes

2023-01-28 20:00 UTC, curiousyigit commented on 1_src/app/controllers/institutions_controller.rb
> +class InstitutionsController < ApplicationController
Por favor autenticar e autorizar o utilizador sempre que necessario. Por exemplo, este vai autenticar e autorizar para todos os actions:
```
before_action :authenticate_user!
before_action { only_allow_user_types(['superadmin', 'admin']) }
```
mas se calhar tu precisas de permitir accesso ao index e show para qualquer utilizador sem autenticacao e autorizacao. Neste caso, podes fazer execao com:
```
before_action :authenticate_user!, :except => [:index, :show]
```
E para autorizacao:
```
before_action -> { only_allow_user_types(['superadmin', 'admin']) }, except: [:index,:show]
```

2023-01-30 01:22 UTC, LammLamm12 commented on 1_src/app/controllers/institutions_controller.rb
> +class InstitutionsController < ApplicationController
Feito

2023-01-30 18:42 UTC, Joselpsantos approved these changes

2023-01-30 18:45 UTC, Joselpsantos submitted a review, later dismissed
É boa prática esconder certos elementos html, como é o caso dos botões para criar, apagar e editar entidades, em caso de dúvidas vê o que está no main.

2023-01-30 19:20 UTC, curiousyigit approved these changes

2023-01-30 19:23 UTC, merged