Feature/ci2 cris 10/article project association
ci2-ipt/Ci2-CRIS pull request #54
Opened 2023-01-28 17:27 UTC by Joselpsantos

Acrescentei o código necessário para ligar os projetos aos artigos bem como editar o projeto a que o artigo pertence

2023-01-28 19:37 UTC, curiousyigit requested changes
Por favor mudar o nome do PR por as nossas convencoes

2023-01-28 20:02 UTC, curiousyigit requested changes

2023-01-28 20:02 UTC, curiousyigit commented on 1_src/app/controllers/articles_controller.rb
>  class ArticlesController < ApplicationController
Por favor autenticar e autorizar o utilizador sempre que necessario. Por exemplo, este vai autenticar e autorizar para todos os actions:
```
before_action :authenticate_user!
before_action { only_allow_user_types(['superadmin', 'admin']) }
```
mas se calhar tu precisas de permitir accesso ao index e show para qualquer utilizador sem autenticacao e autorizacao. Neste caso, podes fazer execao com:
```
before_action :authenticate_user!, :except => [:index, :show]
```
E para autorizacao:
```
before_action -> { only_allow_user_types(['superadmin', 'admin']) }, except: [:index,:show]
```

2023-01-29 13:17 UTC, Joselpsantos commented
> Por favor mudar o nome do PR por as nossas convencoes

Feito

2023-01-29 16:09 UTC, Joselpsantos commented on 1_src/app/controllers/articles_controller.rb
>  class ArticlesController < ApplicationController
> before_action :authenticate_user!, :except => [:index, :show]

Adicionei os mecanismos de autorização mas estão comentados por motivos de conveniência para testar.

2023-01-29 16:27 UTC, curiousyigit commented on 1_src/app/controllers/articles_controller.rb
>  class ArticlesController < ApplicationController
Não foi adicionado os mecanismos de autorização, foi adicionado apenas a autenticação. Qq maneira estou a aprovar

2023-01-29 16:27 UTC, curiousyigit approved these changes

2023-01-29 19:45 UTC, merged